App/Makefile.am, App/configure.ac, Docs/UserGuide/userguide.tex, OREAnalytics/configure.ac, OREData/configure.ac, QuantExt/configure.ac, QuantExt/test/analyticlgmswaptionengine.cpp, QuantExt/test/crossassetmodel.cpp, QuantExt/test/crossassetmodel2.cpp, QuantExt/test/crossassetmodelparametrizations.cpp, QuantExt/test/dynamicblackvoltermstructure.cpp, QuantExt/test/dynamicswaptionvolmatrix.cpp, QuantExt/test/staticallycorrectedyieldtermstructure.cpp, QuantExt/test/utilities.hpp
Running `./configure --with-quantlib-prefix=PREFIX` will add
`-I PREFIX/include` to `CXXFLAGS` and `-L PREFIX/lib to LDFLAGS`.
The installation needs to be made with `make install`; pointing
to where you downloaded or cloned QuantLib won't work.
=> Allow using an already installed QuantLib.

OREAnalytics/orea/aggregation/postprocess.cpp, QuantExt/qle/indexes/inflationindexwrapper.cpp, QuantExt/test/stabilisedglls.cpp
These are three minor edits to make ORE compatible with QuantLib 1.15
For the changes to inflationindexwrapper I've used this commit as a reference:
https://github.com/lballabio/QuantLib/commit/a3f003b8ba8a7d6f9dc3727da7c29e0bb9c417d7#diff-54442c6c948fc489c7811974da4ea87eL134
In two other places, references to boost::function1 are replaced with ext::function, which depends on <ql/function.hpp>, which was only recently added to QuantLib, potentially hindering backwards compatibility of ORE with older versions of QL.
=> Compatibility with QuantLib 1.15

CMakeLists.txt, OREAnalytics/doc/CMakeLists.txt, OREData/doc/CMakeLists.txt, QuantExt/doc/CMakeLists.txt
Move the BUILD_DOC option to the parent CMakeLists.txt and query
its value in the directives which trigger a doxygen build.
=> [chore] Enable option to skip docs generation

OREData/ored/marketdata/strike.cpp, OREData/test/strike.cpp
Hi,
We ran into issues with the commodity delta volatility surface due to the ```AtmStrike::equal_to()``` function. Currently, this throws an exception if ```deltaType_``` is not initialized when dereferenced and fails on lines [711--712](https://github.com/OpenSourceRisk/Engine/blob/a5ee0fc09d5a50ab36e50d55893b6e484d6e7004/OREData/ored/marketdata/commodityvolcurve.cpp#L711) (or [721--722](https://github.com/OpenSourceRisk/Engine/blob/a5ee0fc09d5a50ab36e50d55893b6e484d6e7004/OREData/ored/marketdata/commodityvolcurve.cpp#L721), equivalently) of  ```CommodityVolCurve::buildVolatility(...)```. We change the return statement to not dereference should the variable not be initialized, giving it the intended functionality. The unit test _testAtmStrikeNoDeltaEquality_ is added to verify the …
=> Patch of AtmStrike dereferencing bug

Docs/UserGuide/fixingdata.tex, Docs/UserGuide/userguide.tex
Hi,
We have added some missing options to a table of the ZC inflation indices and additional options the example for EquityCurve configurations. We also correct a missing quote (") to allow for correct usage and syntax highlighting. This aims to check off some of the issues noted in #70. 
Best regards,
SEB
=> Additions to user guide

Docs/UserGuide/userguide.tex, OREData/ored/marketdata/commoditycurve.hpp, QuantExt/qle/math/flatextrapolation.hpp
Hi,
We have had a need of Hermite interpolation for commodity price curves and have added this as an option. It can be toggled by either _"Hermite"_ or _"CubicParabolic"_, although I'd probably suggest excluding the latter for clarity. We have not added test coverage but internal testing has been performed and, additionally, we are basing the change on a previously purchased Quaternion patch for other curve types. 
Best regards,
SEB
=> Hermite interpolation added for commodity curves

QuantExt/qle/pricingengines/crossccyswapengine.cpp, QuantExt/qle/pricingengines/crossccyswapengine.hpp, QuantExt/qle/pricingengines/discountingcurrencyswapengine.cpp, QuantExt/qle/pricingengines/discountingcurrencyswapengine.hpp, QuantExt/qle/termstructures/crossccybasisswaphelper.cpp, QuantExt/qle/termstructures/crossccybasisswaphelper.hpp
The small correction affects the implementation of CrossCcyBasisSwapHelper::initializeDates().
On the line
swap_ = boost::shared_ptr(new CrossCcyBasisSwap( ...
the argument before the last was 0.0 and I replaced it with spreadOnFlatLeg_.
This must be so because only the 5th paySpread argument must be zero.
Otherwise the spreadOnFlatLeg_ would be initialized but nowhere used!
=> Added correct treatment of the spot fx rate settlement in code dealing with cross currency swaps

OREData/OREData.vcxproj, OREData/OREData.vcxproj.filters, OREData/ored/portfolio/asianoption.cpp, OREData/ored/portfolio/asianoption.hpp, OREData/ored/portfolio/builders/asianoption.hpp, OREData/ored/portfolio/builders/commodityasianoption.hpp, OREData/ored/portfolio/builders/equityasianoption.hpp, OREData/ored/portfolio/builders/fxasianoption.hpp, OREData/ored/portfolio/commodityasianoption.cpp, OREData/ored/portfolio/commodityasianoption.hpp, OREData/ored/portfolio/enginefactory.cpp, OREData/ored/portfolio/equityasianoption.cpp, OREData/ored/portfolio/equityasianoption.hpp, OREData/ored/portfolio/fxasianoption.cpp, OREData/ored/portfolio/fxasianoption.hpp, OREData/ored/portfolio/optionasiandata.cpp, OREData/ored/portfolio/optionasiandata.hpp, OREData/ored/portfolio/optiondata.cpp, OREData/ored/portfolio/optiondata.hpp, OREData/ored/portfolio/tradefactory.cpp, OREData/ored/utilities/parsers.cpp, OREData/ored/utilities/parsers.hpp, OREData/test/OREDataTestSuite.vcxproj, OREData/test/OREDataTestSuite.vcxproj.filters, OREData/test/commodityasianoption.cpp, OREData/test/equityasianoption.cpp, OREData/test/fxasianoption.cpp, OREData/test/optionasiandata.cpp
Hi, Roland and team!
We're happy to share our perhaps biggest implementation, thus far at least, of Asian options in ORE. In short, we link six QL pricing engines to cover discrete/continuous averaging of arithmetic/geometric average price/strike options. Down below I will try to describe the implementation and any design choices made, before I can get to adding it into the user guide as well. There may well be many questionable choices so I will prematurely give a disclaimer that we have many things to learn still :slightly_smiling_face: A few things still remain to be listed, which I will strive to do shortly, but I will share this as a draft to open up for discussion in the meantime. 
We followed suit from the `VanillaOptionTrade` implementation in OREData and created an …
=> Commodity/Equity/FX Asian option trade support

Examples/Input/pricingengine.xml, OREData/ored/portfolio/builders/vanillaoption.hpp
Hi all,
In our developments, we created a "Greeks report" written from the `ReportWriter` after the standard reports. We use this report to print the Greeks of vanilla options (currently only being QL's `OneAssetOption`) where we noticed poor performance due to the grid choices in `AmericanOptionFDEngineBuilder` for short expiries. This is directly related to a [QL discussion](https://github.com/lballabio/QuantLib/issues/779) from a few years back. It becomes an issue when expiry is around 2 weeks or less, for example: when expiry is in 7 days, we have `t = 0.0192` times `TimeGridPerYear = 100`, yielding `tGrid = 1` currently.
I see a few solutions to this which I'll list below:
1. Greatly increase _TimeGridPerYear_ in the _pricingengine.xml_ - simple (no coding) but inefficient for …
=> Grid change for AmericanOptionFDEngineBuilder

xsd/curveconfig.xsd, xsd/ore_types.xsd
Hi all,
This is a fix for the newly added interpolation methods to be added into the XSD enum. We noticed that we had overlooked this previously. 
On a side note, the Asian options will also be missing from the XSDs, though we'll strive to help with adding this soon. The same goes for extending their documentation. 
I also wish to give a sincere thank you for your maintaining of ORE and the release of version 6. We'll be looking forward to contribute more.
Best regards,
SEB
=> Add missing interpolation enums to XSD

App/ore.vcxproj
Hi all,
Here's a fix to close #80 that prevents building the VS solution when not having a specific Windows SDK version. This minor retarget lessens the requirements on the user as noted in the issue.
Best regards,
SEB
=> Retarget VS project to use latest available Windows SDK

OREData/OREData.vcxproj.filters
Hi,
It seems the filters for some of the Asian option files got lost in the ether during the ORE 6 upgrade. Here's a quick fix to bring them back.
Best regards,
SEB
=> Add missing filter for Asian option files

Docs/UserGuide/allowablevalues.tex, xsd/ore_types.xsd
Hi all,
We have noticed that Euribor365 is correctly parsed within `parseIborIndex()` although it is rejected by the XSD regex for _indexNameType_ and not listed in the user guide. I have added support for this, allowing an optional 365 in the index name, as it helps us distinguish trades in our portfolios and avoids messing up the daycounts. 
Best regards,
SEB
=> Add Euribor365 to XSD and user guide

OREData/ored/portfolio/capfloor.hpp
Hi!
Cap and floor trades had their cashflow outputs suppressed in the ORE 5 release which I believe they should not have. I have removed the overridden function to allow the printing once again as it helps greatly in the validation of trades, seeing as caps/floors don't produce any additional results or data yet. I am intending on doing something about that soon, at least such that the vols used for each cashflow may be extracted. 
Best regards,
SEB
=> Print cashflows of cap/floor trades

OREData/ored/configuration/equityvolcurveconfig.hpp, QuantExt/qle/termstructures/equityblackvolsurfaceproxy.hpp
Hi,
This fixes three minor issues relating to equity proxy vols:
- The include guard of the class in _equityblackvolsurfaceproxy.hpp_ no longer duplicates/redefines the one from _blackvolsurfacewithatm.hpp_, to avoid any problems.
- The docstring was updated to reflect the correct file/class.
- The inspector for proxy vols was marked as `const`.
Best,
Fredrik
SEB
=> Minor fixes for equity proxy volatility surfaces

OREData/ored/portfolio/builders/asianoption.hpp, OREData/ored/portfolio/builders/commodityasianoption.hpp, OREData/ored/portfolio/builders/equityasianoption.hpp, OREData/ored/portfolio/builders/fxasianoption.hpp, OREData/ored/portfolio/enginefactory.cpp
Hi there,
We have recently PR'd the Turnbull-Wakeman moment-matching engine to QL, available to be used when pricing Asian options in ORE. We have used it successfully on our end and hopefully you might have some interest in it as well.
Notably, the engine will be available with QL 1.27 so previous build may fail until ORE is updated to run v1.27 (or later versions). Hopefully this may happen with ORE 7? :) If not, we could add preprocessor directives to conditionally include the engine if the QL version is recent enough.
Best,
Fredrik
SEB
=> Map TW engine for arithmetic average price options

OREData/ored/marketdata/marketdatumparser.cpp
Hi,
Trivial change that removes the double mapping of "FX_FWD" found in `parseInstrumentType`.
=> Remove duplicate FX_FWD key mapping

QuantExt/qle/pricingengines/discountingfxforwardengine.cpp
Matching the meaning of the QL_REQUIRE expression with the exception description for physical-settled Fx Forward trade:
`QL_REQUIRE(arguments_.isPhysicallySettled || arguments_.payDate <= arguments_.fixingDate || arguments_.fxIndex != nullptr, "If pay date (" << arguments_.payDate << ") is strictly after fixing date (" << arguments_.fixingDate << "), an FX Index must be given for a cash-settled FX Forward.");`
=> Fix QL_REQUIRE for physical-settled FX Forward

Docs/UserGuide/curve_configurations/yieldcurves.tex
Corrects a discrepancy between the actual code and the yield curve example config.
=> Fix YieldCurveDayCounter field in example

Docs/UserGuide/allowablevalues.tex
Hi,
This adds a few missing entries and adds the correct mapping for the 30/360 Bond Basis convention.
=> Adjust table for day-count method mappings

cmake/commonSettings.cmake
Use CheckLinkerFlag in supported CMake version 3.18 or greater. Fixes issue #181
=> Use CheckLinkerFlag in CMake supported version >=3.18

Docs/UserGuide/tradecomponents/legdatanotionals.tex, OREData/ored/portfolio/legdata.cpp, QuantExt/qle/cashflows/cpicoupon.cpp, QuantExt/qle/cashflows/cpicoupon.hpp, QuantExt/test/CMakeLists.txt, QuantExt/test/cpileg.cpp
Hi,
We price inflation swaps/bonds using these two legs types and we see quite a big valuation impact by the lack of payment lag. This PR makes use of the PaymentLag field and adjusts the relevant payment dates accordingly.
A test is added for the CPI leg case, and the user guide is updated to mention the added support.
=> Apply payment lag for CPI and Zero Coupon Fixed legs

OREData/ored/marketdata/fxvolcurve.cpp
Hi,
The user guide mentions "Cubic" as a valid smile interpolation method for FX delta skews, though the field is never applied. This PR adds parsing of the field and maps Linear/CubicSpline correctly depending on the input.
=> Bug fix: Apply smile interpolation from FX delta surface config

xsd/conventions.xsd
Hi,
We noticed this element was missing after we extended our set of conventions.
=> Add ValidContractMonths to commodity future convention XSD

Docs/UserGuide/curve_configurations/yieldcurves.tex, Docs/UserGuide/marketdata.tex, OREData/ored/marketdata/yieldcurve.cpp, OREData/test/yieldcurve.cpp
It will also improve the performance when reading market data since it will be read once instead
of looping the market data for each quote.
Testing that both using all quotes for segments like before work but now also a convenient usage with wildcard
works for example:
```
<Segments>
<Direct>
<Type>Discount</Type>
<Quotes>
<Quote>DISCOUNT/RATE/EUR/EUR3M/*</Quote>
</Quotes>
<Conventions/>
</Direct>
</Segments>
```
Updated document with this change.
Also corrected mistake in example document that Discount quote does not use day count convention.
=> Enable usage of wildcard quote for direct yield curve segments

App/CMakeLists.txt, CMakeLists.txt, OREAnalytics/CMakeLists.txt, OREData/CMakeLists.txt, QuantExt/CMakeLists.txt
Specifying a search path for CMake modules to be loaded by the include() or find_package() is more robust for cmake three changes. It is intended to be set by the project.
=> Use CMAKE_MODULE_PATH

.github/workflows/build_windows.yaml, .github/workflows/linux_build.yaml, .github/workflows/macos_ARM64_build.yaml
Hi,
This resolves the warning shown in the action run here: https://github.com/OpenSourceRisk/Engine/actions/runs/8184916349
=> Bump actions to v4 for Node20

OREData/ored/utilities/parsers.cpp, OREData/test/parser.cpp
This came up as "unsupported" in the additional results of some instrument.
Added test to verify output of ccy name.
=> Add support to parse Currency from Boost::Any

cmake/commonSettings.cmake
The Boost configuration now includes support for Linux, providing the flexibility to choose between optional static or dynamic linking on this platform. Previously, only shared system linking was feasible. In our company's use case, there is a requirement to create a standalone application for Linux, linked statically with Boost.
With the unified configuration of Boost for both Linux and Windows, we can streamline the code into a common space, enhancing code organization and maintainability.
=> Link Boost static or dynamic for Linux

Docs/UserGuide/parameterisation/curveconfig.tex, OREData/ored/configuration/fxvolcurveconfig.cpp, OREData/ored/configuration/fxvolcurveconfig.hpp, OREData/ored/marketdata/fxvolcurve.cpp, xsd/curveconfig.xsd
Hi,
We find it useful to allow toggling the extrapolation method, which currently would default to 'Flat' for delta skews. The code changes here are borrowed from the commodity delta volatility implementation, following the same logic.
I'll mark the PR as ready once we've extended the docs and XSDs.
Thanks!
Fredrik
=> Allow toggling extrapolation method for FX delta smiles

xsd/calendaradjustment.xsd, xsd/conventions.xsd, xsd/creditsimulation.xsd, xsd/iborfallbackconfig.xsd, xsd/instruments.xsd, xsd/nettingsetdefinitions.xsd, xsd/referencedata.xsd, xsd/sensitivity.xsd, xsd/simulation.xsd, xsd/stress.xsd, xsd/todaysmarket.xsd
Hi!
Our IDE (PyCharm) used when developing our integrations against ORE makes a big fuss about the XSDs not including all of their dependencies.
=> Make XSD files include all schema dependencies

CMakePresets.json
Adding support for Apple M-series arm chipset to CMakePresets.
=> Add Apple arm64 CMakePreset

Docs/UserGuide/conventions.tex
Hi,
These two fields are missing from the guide. Adding them makes it easier to generate the correct FX conventions.
=> Extend FX convention documentation
