OpenSourceRisk/Engine

- tools/docker/Dockerfile
- tools/docker/README.md
Make of this what you will.  It's part experiment, and part step towards my Hacktoberfest quota. 😄 
I won't complain if you don't merge it.
The container mostly works, with a few caveats which I described in the README. It might be a way to kick the Engine tires on Linux or Mac OS X before committing to installing the prerequisites and compiling the whole thing. Then again, it might be a bit too technical if one is not familiar with Docker.  Your call...
> Add Dockerfile to build sample image.

- Docs/UserGuide/marketdata.tex
- Docs/UserGuide/portfoliodata.tex
- xsd/instruments.xsd
added missing NotionalAmortizingExchange element in instruments.xsd #12 
updated marketdata and portfoliodata documentation. #12 
I've also added Instrument Type and Quote Type to each market data item, as it was sometimes confusing without having this info (just "guessing" from the examples).
> updated marketdata and portfoliodata documentation.

- OREData/ored/utilities/indexparser.cpp
Added EURIBOR365, will also change the docs so that it would contain all the indexes.
> Added index EURIBOR365

- QuantExt/qle/instruments/crossccybasisswap.cpp
- QuantExt/qle/instruments/crossccybasisswap.hpp
- QuantExt/qle/termstructures/crossccybasisswaphelper.cpp
- QuantExt/qle/termstructures/crossccybasisswaphelper.hpp
Added two new parameters to the CrossCcyBasisSwap constructor that define the Gearing of the two legs.
Added 5 new parameters to the CrossCcyBasisSwapHelper constructor that define an optional spread on the flat leg as well as the Gearing and Calendar of the two legs.
> Added new parameters to the CrossCcyBasisSwap and CrossCcyBasisSwapHelper constructors

- OREAnalytics/orea/scenario/scenariosimmarket.cpp
- OREAnalytics/orea/scenario/scenariosimmarket.hpp
- QuantExt/qle/termstructures/interpolateddiscountcurvelinearzero.hpp
- QuantExt/test/discountcurve.cpp
This PR is to allow linear interpolation in the zero rate for yield curves during the simulation.
> Allow linear interpolation in the zero rate in the simulation

- OREData/ored/marketdata/capfloorvolcurve.cpp
Hi!
This closes #90 if the suggested solution is agreed upon. If not, let me know and I will try to implement any other suggestions. 
Best regards,
SEB
> Extrapolation of cap/floor volatilities

- OREData/ored/portfolio/asianoption.cpp
Hi,
Since last year, a new preferred constructor was added to the class `DiscreteAveragingAsianOption` in QuantLib. It mainly changed how the dates of the fixings are passed, so this PR makes the required changes in ORE's Asian option builder to accommodate for that. The PR also includes some simplification of the logic used to read past fixings and cleanup of comments.
All applicable tests pass, still.
Best,
Fredrik
SEB
> Upgrade Asian option builder to use new constructor

- Docs/UserGuide/userguide.tex
Dear Peter!
As discussed the corrected user-guide for the cross-gamma part.
-regards,
Roland
> corrected cross gamma file being incorporated in sensitivity file

- Docs/UserGuide/userguide.tex
Dear Peter, I've added the explanations that we discussed today.
> added explanations for LGM model calibration configuration (options)

- Docs/UserGuide/userguide.tex
Dear Peter, I added some comments to hopefully avoid the version confusion in #121
> Added warning/advice for building ORE-SWIG

- Docs/UserGuide/userguide.tex
Dear all, I added the results of Matthias' hints to the CMake features of Visual Studio in #136 to the Userguide.
> Added Use of Visual Studio's CMake capabilities

- Docs/UserGuide/curve_configurations/commodity_volatilities.tex
- Docs/UserGuide/tradedata/commodityapo.tex
Hi,
This adds a missing description and fixes a typo in another tag for the commodity volatility delta config.
> Fix description of commodity delta vol fields

- QuantExt/qle/instruments/brlcdiswap.cpp
* fixedLegBPS sign was wrong
* fairRate has to be the same for Payer and Receiver swaps
> Fix fixedLegBPS and fairRate for BRLCdiSwap

- Docs/UserGuide/tradecomponents/underlying.tex
- OREAnalytics/orea/app/marketdataloader.cpp
- OREData/ored/configuration/conventions.cpp
- OREData/ored/portfolio/barrieroption.cpp
- OREData/ored/portfolio/barrieroption.hpp
- OREData/ored/portfolio/equitybarrieroption.cpp
- OREData/ored/portfolio/equitybarrieroption.hpp
- OREData/ored/portfolio/equitydoublebarrieroption.cpp
- OREData/ored/portfolio/equitydoublebarrieroption.hpp
- OREData/ored/portfolio/fxbarrieroption.cpp
- OREData/ored/portfolio/fxbarrieroption.hpp
- OREData/ored/portfolio/fxdoublebarrieroption.cpp
- OREData/ored/portfolio/fxdoublebarrieroption.hpp
- QuantExt/qle/calendars/islamicweekendsonly.hpp
Hi,
Here's a collection of minor text fixes we have accrued over some time on our fork.
> Textual fixes to logs, errors, user guide

- .github/workflows/linux_build.yaml
Missing pipeline in this project. As a start I just added a workflow for Ubuntu 22.04. 
If it is ok for the maintainers of this repo I would also like add tests checks and then Windows workflows since it seems many users are using this project in Windows. This will help considerable in contributing to this project.
> Suggestion to add first GitHub Action for Linux build

- .github/workflows/linux_build.yaml
Forgot add Ninja package. Sorry... :)
> Bugfix/add ninja to GitHub runner

- xsd/curveconfig.xsd
- xsd/instruments.xsd
Hi,
We rely on these XSD extensions internally and hope others may find them helpful as well.
> Correct XSD for missing report configuration elements

- CMakePresets.json
> Add Linux clang CMake presets

- .github/workflows/build_windows.yaml
- .github/workflows/linux_build.yaml
This PR add a Windows CI pipeline building with MSVC 14.3. 
Downgraded boost to 1.72 for issue with #160.
I wonder if some with repo settings access can add these 2 CI checks on all contributions to validate and give contributors a badge. :)
Thank you!
kohnech
> Add windows GitHub action

- Examples/Example_44/ExpectedOutput/SIMM2.6_10D/simm.csv
- Examples/Example_44/Input/ore_SIMM2.6_10D.xml
- OREAnalytics/orea/app/analytics/simmanalytic.hpp
- OREAnalytics/orea/app/inputparameters.hpp
- OREAnalytics/orea/app/oreapp.cpp
CSV separator can be specified. Optionally disable intermediate SIMM reports.
> Allow customization of Csv and SIMM intermediate reports in master input file

- OREAnalytics/orea/app/inputparameters.cpp
- OREAnalytics/orea/app/inputparameters.hpp
- OREAnalytics/orea/app/oreapp.cpp
- OREAnalytics/orea/app/oreapp.hpp
This makes it easier to use central configuration files.
> Allow absolute pathes in master input file

- Docs/UserGuide/userguide.tex
- OREAnalytics/test/CMakeLists.txt
- OREData/ored/portfolio/commodityforward.cpp
- fixed userdoc simulation.xml example AggregationScenarioDataCurrencies and AggregationScenarioDataIndices.
> Fix of ABI Problem, commodity forward notional and userdoc improvements

- xsd/calendaradjustment.xsd
- xsd/conventions.xsd
- xsd/creditsimulation.xsd
- xsd/iborfallbackconfig.xsd
- xsd/instruments.xsd
- xsd/nettingsetdefinitions.xsd
- xsd/referencedata.xsd
- xsd/sensitivity.xsd
- xsd/simulation.xsd
- xsd/stress.xsd
- xsd/todaysmarket.xsd
Reverts OpenSourceRisk/Engine#214
> Revert "Make XSD files include all schema dependencies"
